/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  safelist: [
    'text-brand-primary',
    'bg-brand-primary',
    'bg-brand-secondary',
    'text-status-success',
    'bg-status-success-light',
    'text-status-warning',
    'bg-status-warning-light',
    'text-status-error',
    'bg-status-error-light',
    'border-status-success',
    'border-status-warning',
    'border-status-error',
    'hover:bg-brand-primary-dark',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          primary: 'var(--brand-primary)',
          'primary-dark': 'var(--brand-primary-dark)',
          'primary-light': 'var(--brand-primary-light)',
          secondary: 'var(--brand-secondary)',
          'secondary-dark': 'var(--brand-secondary-dark)',
          'secondary-light': 'var(--brand-secondary-light)',
          accent: 'var(--brand-accent)',
          'accent-dark': 'var(--brand-accent-dark)',
          'accent-light': 'var(--brand-accent-light)',
          cta: 'var(--brand-cta)',
          'cta-dark': 'var(--brand-cta-dark)',
          'cta-light': 'var(--brand-cta-light)',
        },
        neutral: {
          100: 'var(--neutral-100)',
          200: 'var(--neutral-200)',
          500: 'var(--neutral-500)',
          900: 'var(--neutral-900)',
        },
        status: {
          success: 'var(--status-success)',
          'success-light': 'var(--status-success-light)',
          'success-dark': 'var(--status-success-dark)',
          warning: 'var(--status-warning)',
          'warning-light': 'var(--status-warning-light)',
          'warning-dark': 'var(--status-warning-dark)',
          error: 'var(--status-error)',
          'error-light': 'var(--status-error-light)',
          'error-dark': 'var(--status-error-dark)',
        },
        vis: {
          'cat-1': 'var(--vis-cat-1)',
          'cat-2': 'var(--vis-cat-2)',
          'cat-3': 'var(--vis-cat-3)',
          'cat-4': 'var(--vis-cat-4)',
          'cat-5': 'var(--vis-cat-5)',
          'cat-6': 'var(--vis-cat-6)',
          'div-1': 'var(--vis-div-1)',
          'div-2': 'var(--vis-div-2)',
          'div-3': 'var(--vis-div-3)',
          'div-4': 'var(--vis-div-4)',
          'div-5': 'var(--vis-div-5)',
        },
      },
      width: {
        '112': '448px', // Custom width for field group sidebar
      },
      spacing: {
        'safe-area-inset-bottom': 'env(safe-area-inset-bottom)',
        'safe-area-inset-top': 'env(safe-area-inset-top)',
        'safe-area-inset-left': 'env(safe-area-inset-left)',
        'safe-area-inset-right': 'env(safe-area-inset-right)',
      },
      height: {
        'safe-area-inset-bottom': 'env(safe-area-inset-bottom)',
        'safe-area-inset-top': 'env(safe-area-inset-top)',
      },
      padding: {
        'safe-area-inset-bottom': 'env(safe-area-inset-bottom)',
        'safe-area-inset-top': 'env(safe-area-inset-top)',
        'safe-area-inset-left': 'env(safe-area-inset-left)',
        'safe-area-inset-right': 'env(safe-area-inset-right)',
      },
      margin: {
        'safe-area-inset-bottom': 'env(safe-area-inset-bottom)',
        'safe-area-inset-top': 'env(safe-area-inset-top)',
        'safe-area-inset-left': 'env(safe-area-inset-left)',
        'safe-area-inset-right': 'env(safe-area-inset-right)',
      },
    },
  },
  plugins: [],
};
